version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderservice
      MYSQL_USER: abc
      MYSQL_PASSWORD: def
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8082:80"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql #http://127.0.0.1:0:3306/orderservice
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      # PMA_HOST: mysql-15fd6dfe-francisco-a453.k.aivencloud.com
      # PMA_USER: avnadmin
      # PMA_PASSWORD: AVNS_udjuRIGT8yd5B2PIwo6
    networks:
      - my-network

  order-service:
      container_name: order-api
      build:
        context: .
        dockerfile: Dockerfile
      # restart: always
      links:
        - mysql:mysql
      depends_on:
        - mysql
      environment:
        # - DATABASE_HOST=mysql-15fd6dfe-francisco-a453.k.aivencloud.com
        # - DATABASE_PORT=22132
        # - DATABASE_NAME=defaultdb
        # - DATABASE_USER=avnadmin
        # - DATABASE_PASSWORD=AVNS_udjuRIGT8yd5B2PIwo6
        - DATABASE_HOST=mysql
        - DATABASE_PORT=3306
        - DATABASE_NAME=orderservice
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
      ports:
        - 8081:8081
      networks:
        - my-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker-config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
        - my-network
    depends_on:
      - order-service

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
        - my-network
    depends_on:
      - order-service

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./docker-config/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./docker-config/grafana/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yml
      - ./docker-config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
        - my-network
    depends_on:
      - prometheus

networks:
  my-network:
    name: internal
    # driver: bridge

# Volumes
volumes:
  db-data:
    driver: local