version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderservice
      MYSQL_USER: abc
      MYSQL_PASSWORD: def
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8082:80"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql #http://127.0.0.1:0:3306/orderservice
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - my-network

  order-service:
      container_name: order-api
      build:
        context: .
        dockerfile: Dockerfile
      # restart: always
      links:
        - mysql:mysql
      depends_on:
        - mysql
      ports:
        - 8081:8081
      networks:
        - my-network

networks:
  my-network:
    name: internal
    # driver: bridge

# Volumes
volumes:
  db-data:
    driver: local