name: build spring-api

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    name: build-test spring-api
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          context: ${{ github.workspace }}/orderservice/
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/orderservice/
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rest-api:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/orderservice/
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rest-api:latest
